CSV Save Feature
raymondwzeng/cs180-housing-project pull request #55
Opened 2022-04-25 18:59 UTC by raymondwzeng

## Major Changes
Added a new function to `csv.js`, aptly named save. This saves a specific set of data to a specific path on disk. This should only be called from the Operations layer.

I also added 3 unit tests that messes with the data and ensures that the data is readable afterwards. There's a non-zero chance that the tests won't run as an entire suite due to the messing around with data, but feel free to run it with mocha on its own.

2022-04-25 19:03 UTC, tgustafson2 approved these changes
Looks good to me

2022-04-25 21:58 UTC, dukeph0 approved these changes
I approve

2022-04-25 22:06 UTC, AaronGeesink requested changes
On second glance, It seems that some of the changes you made broke some of the unit tests. Please figure out why they are breaking, and fix them before you go ahead and merge into main. The broken test cases are all in the Operations layer. Maybe you accidentally saved to the California_Houses.csv file when making the save function? I will admit that the Operation Layer unit tests are really finnicky and could benefit from a second opinion.

2022-04-27 23:46 UTC, raymondwzeng commented
Lots of refactoring. Things should be alright now.

![image](https://user-images.githubusercontent.com/13594022/165649004-f3860112-bf59-40cd-bad2-1946bf6e7681.png)

2022-04-28 01:54 UTC, AaronGeesink approved these changes
unit tests now pass consistently no matter how many times we call `npm test` AND we finally have unit tests for all `api/cards`  endpoints. Good work, let's merge.

2022-04-28 01:54 UTC, merged

2022-04-28 01:56 UTC, AaronGeesink commented on server/test/apiTest.js
> +                expect(res.body.length).to.be.equal(20641)
It's possible this unit test (and similar ones that have a hardcoded length in them) will potentially have to be changed in the future if we end up saving to the original csv file. However, for now this seems like an alright approach.